got a new error message! so now testing that we can install jekyll properly

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,13 +72,21 @@ jobs:
         with:
           ruby-version: "3.1.4"
           bundler-cache: false
-      - name: Debug Ruby Version 🐛
-        run: ruby -v
+      - name: Confirm Ruby Version 📢
+        run: |
+          which ruby
+          ruby -v
       - name: Setup Python 🐍
         uses: actions/setup-python@v5
         with:
           python-version: "3.13"
           cache: "pip" # caching pip dependencies
+      - name: Check Binaries 🧪
+        run: |
+          which bundle
+          bundle -v
+          which jekyll
+          jekyll -v || echo "Jekyll not found"
       - name: Update _config.yml ⚙️
         uses: fjogeleit/yaml-update-action@main
         with:
@@ -90,7 +98,9 @@ jobs:
         run: |
           pip3 install --upgrade nbconvert
           export JEKYLL_ENV=production
-          bundle exec jekyll build
+          gem install bundler
+          bundle install --verbose
+          bundle exec jekyll build --trace
       - name: Purge unused CSS 🧹
         run: |
           npm install -g purgecss
